// import fetch from "node-fetch";
// import { SHOPIFY_API_VERSION } from "./ShopifyOAuthService.js";

// // REST helper for a specific shop + token
// async function shopifyREST(shop, token, method, path, body = null) {
//   const url = `https://${shop}/admin/api/${SHOPIFY_API_VERSION}/${path}`;
//   const res = await fetch(url, {
//     method,
//     headers: {
//       "X-Shopify-Access-Token": token,
//       "Content-Type": "application/json",
//     },
//     body: body ? JSON.stringify(body) : undefined,
//   });

//   const text = await res.text();
//   let data = {};
//   try { data = text ? JSON.parse(text) : {}; } catch (e) {
//     throw new Error(`Shopify non-JSON response: ${text}`);
//   }
//   if (!res.ok) {
//     throw new Error(`Shopify REST Error (${res.status}): ${JSON.stringify(data)}`);
//   }
//   return data;
// }

// // GraphQL helper (for product creation)
// async function shopifyGraphQL(shop, token, query, variables = {}) {
//   const url = `https://${shop}/admin/api/${SHOPIFY_API_VERSION}/graphql.json`;
//   const res = await fetch(url, {
//     method: "POST",
//     headers: {
//       "X-Shopify-Access-Token": token,
//       "Content-Type": "application/json",
//     },
//     body: JSON.stringify({ query, variables }),
//   });
//   const data = await res.json();
//   if (data.errors) throw new Error(`Shopify GraphQL Error: ${JSON.stringify(data.errors)}`);
//   return data.data;
// }

// // Main provisioning: simple Welcome page + default product
// export async function provisionShopifyStore(shop, token, storeName) {
//   const result = {};

//   // 1) Welcome page
//   const pagePayload = {
//     page: {
//       title: "Welcome",
//       body_html: `<h1>${storeName}</h1><p>Auto-generated by HiveHub.</p>`,
//     },
//   };
//   const createdPage = await shopifyREST(shop, token, "POST", "pages.json", pagePayload);
//   result.page = createdPage.page;

//   // 2) Default product
//   const mutation = `
//     mutation productCreate($input: ProductInput!) {
//       productCreate(input: $input) {
//         product { id title handle }
//         userErrors { field message }
//       }
//     }
//   `;
//   const vars = {
//     input: {
//       title: `${storeName} Default Product`,
//       descriptionHtml: `<p>Auto created for ${storeName}</p>`,
//     },
//   };
//   const productData = await shopifyGraphQL(shop, token, mutation, vars);
//   if (productData.productCreate.userErrors?.length) {
//     throw new Error(JSON.stringify(productData.productCreate.userErrors));
//   }
//   result.product = productData.productCreate.product;

//   // (Optional: add theme / assets later)

//   return result;
// }











// backend/services/ShopifyProvisionService.js
import fetch from "node-fetch";
import { SHOPIFY_API_VERSION } from "./ShopifyOAuthService.js";
import Product from "../model/product.model.js"; 
import User from "../model/user.model.js";
import axios from "axios";
// import { fetchCJProducts } from "../services/CJProductService.js";

/**
 * Generic REST helper for Shopify Admin API
 */
export async function shopifyREST(shop, token, method, path, body = null) {
  const url = `https://${shop}/admin/api/${SHOPIFY_API_VERSION}/${path}`;

  const res = await fetch(url, {
    method,
    headers: {
      "X-Shopify-Access-Token": token,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  const text = await res.text();
  let data = {};
  try {
    data = text ? JSON.parse(text) : {};
  } catch (e) {
    console.error("❌ Shopify non-JSON response:", text);
    throw new Error(`Shopify non-JSON response (status ${res.status})`);
  }

  if (!res.ok) {
    console.error(`❌ Shopify REST Error (${res.status}):`, data);
    throw new Error(`Shopify REST Error: ${JSON.stringify(data)}`);
  }

  return data;
}

/**
 * Minimal GraphQL helper (we only use it for productCreate)
 */
async function shopifyGraphQL(shop, token, query, variables = {}) {
  const url = `https://${shop}/admin/api/${SHOPIFY_API_VERSION}/graphql.json`;

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "X-Shopify-Access-Token": token,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query, variables }),
  });

  const data = await res.json();
  if (data.errors) {
    console.error("❌ Shopify GraphQL errors:", data.errors);
    throw new Error(`Shopify GraphQL Error: ${JSON.stringify(data.errors)}`);
  }

  return data.data;
}

/**
 * Get the current main (published) theme ID
 */
async function getMainThemeId(shop, token) {
  const data = await shopifyREST(shop, token, "GET", "themes.json");
  const mainTheme = (data.themes || []).find((t) => t.role === "main");
  return mainTheme ? mainTheme.id : null;
}

/**
 * Inject a simple CSS file into the main theme so you have a visible sign
 * that HiveHub customised the theme.
 */
async function applyBasicThemeTweaks(shop, token, storeName) {
  const themeId = await getMainThemeId(shop, token);
  if (!themeId) {
    console.warn("⚠️ No main theme found, skipping CSS injection");
    return;
  }

  const css = `
/* Injected by HiveHub for store: ${storeName} */
h1, .h1 {
  color: #4f46e5 !important; /* Indigo */
}
  `;

  await shopifyREST(
    shop,
    token,
    "PUT",
    `themes/${themeId}/assets.json`,
    {
      asset: {
        key: "assets/hivehub.css",
        value: css,
      },
    }
  );

  console.log(`✅ Injected hivehub.css into theme ${themeId}`);
}

/**
 * Create a simple "Welcome" page
 */
async function createWelcomePage(shop, token, storeName) {
  const payload = {
    page: {
      title: "Welcome",
      body_html: `<h1>Welcome to ${storeName}</h1><p>This page was auto-generated by HiveHub.</p>`,
    },
  };

  const res = await shopifyREST(shop, token, "POST", "pages.json", payload);
  console.log("✅ Created Welcome page:", res.page?.id);
  return res.page;
}


async function syncHiveHubProductsToShopify(shop, token, hiveProducts, hiveStore) {
  console.log("📦 Syncing HiveHub products -> Shopify ...");

  if (!hiveProducts.length) {
    console.log("⚠️ No HiveHub products found — skipping product sync");
    return [];
  }

  const createdProducts = [];

  for (const p of hiveProducts) {
    try {
      const body = {
        product: {
          title: p.name,
          body_html: `<p>${p.description || ""}</p>`,
          product_type: p.category || "General",
          vendor: hiveStore.name,
          variants: [
            {
              price: `${p.price || "0.00"}`,
            }
          ],
          images: p.image ? [{ src: p.image }] : []
        }
      };

      console.log("📤 Sending REST Product Payload:", JSON.stringify(body, null, 2));

      const response = await shopifyREST(shop, token, "POST", "products.json", body);

      console.log("✅ Created Shopify product:", response.product.title);
      createdProducts.push(response.product);

    } catch (err) {
  console.error("❌ Shopify create error:", err.message);
  if (err.response?.data) console.error("🔍 Shopify details:", err.response.data);
}
  }

  return createdProducts;
}



async function fetchCJProducts() {
  try {
    const response = await axios.get(
      "https://developers.cjdropshipping.com/api2.0/v1/product/list",
      {
        params: { pageNum: 1, pageSize: 100 },
        headers: {
          "CJ-Access-Token": `Bearer ${process.env.CJ_TOKEN}`,
        },
      }
    );

    const list = response.data?.data?.list || [];

    return list.map((item) => ({
      name: item.name || "Unnamed Product",
      description: item.description || "",
      // price: item.price || 0,
      price: item.sellPrice || item.retailPrice || 0,
      // image: item.productImage || null,
      image: item.productImage || item.productImages?.[0] || null,
      category: item.category || "General",
    }));
  } catch (err) {
    console.error("❌ Failed to fetch CJ products", err.response?.data || err);
    return [];
  }
}




/**
 * MAIN ENTRY:
 * Provision Shopify store when app is installed.
 * This runs once during OAuth callback.
 */
export async function provisionShopifyStore(shop, token, hiveStore) {
    console.log(`🚀 Provisioning Shopify store for "${hiveStore.name}" (${shop})`);
  console.log("🔎 HiveStore object:", hiveStore);
  const storeName = hiveStore.name;
  const category = hiveStore.category;

  console.log(`🚀 Provisioning Shopify store for "${storeName}" (${shop})`);

  // Log products before attempting sync
const user = await User.findById(hiveStore.ownerId);
// const hiveProducts = user?.myProducts || [];
// console.log(`📦 Found ${hiveProducts.length} HiveHub products for owner`, hiveStore.ownerId);


// Load DB products
const dbProducts = user?.myProducts || [];

// Load CJ API products
const apiProducts = await fetchCJProducts();

console.log(`📦 DB products: ${dbProducts.length}`);
console.log(`📦 API products: ${apiProducts.length}`);

// Merge both sets
const hiveProducts = [...dbProducts, ...apiProducts];

console.log(`📦 Total products to sync: ${hiveProducts.length}`);



  const result = {};

  // 1) Welcome page
  result.page = await createWelcomePage(shop, token, storeName);

  // 2) Demo products
//   result.products = await createDemoProducts(shop, token, storeName, category);

// 2) Sync real HiveHub products
// result.products = await syncHiveHubProductsToShopify(shop, token, hiveStore);

// result.products = await syncHiveHubProductsToShopify(shop, token, hiveProducts);
result.products = await syncHiveHubProductsToShopify(shop, token, hiveProducts, hiveStore);





  // 3) Theme tweaks (inject CSS)
  await applyBasicThemeTweaks(shop, token, storeName);

  console.log("✅ Shopify provisioning complete");
  return result;
}
